[2024-01-09 12:52:37] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-01-09 12:52:37] [INFO    ] discord.client: logging in using static token
[2024-01-09 12:52:37] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 77a5ecab54a8f319116fdfd457a3b315).
[2024-01-09 14:07:09] [ERROR   ] discord.client: Attempting a reconnect in 0.22s
Traceback (most recent call last):
  File "/home/mathew_wiltshire/.local/lib/python3.9/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/mathew_wiltshire/.local/lib/python3.9/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
[2024-01-09 14:07:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-09 17:14:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-09 19:40:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-09 21:58:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-09 23:15:55] [WARNING ] discord.gateway: Can't keep up, shard ID None websocket is 13.5s behind.
[2024-01-10 00:17:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-10 03:41:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-10 06:11:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-10 08:39:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-10 10:23:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-10 11:58:16] [ERROR   ] discord.client: Attempting a reconnect in 0.67s
Traceback (most recent call last):
  File "/home/mathew_wiltshire/.local/lib/python3.9/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/mathew_wiltshire/.local/lib/python3.9/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
[2024-01-10 11:58:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
[2024-01-10 12:06:06] [ERROR   ] discord.client: Attempting a reconnect in 0.71s
Traceback (most recent call last):
  File "/home/mathew_wiltshire/.local/lib/python3.9/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/mathew_wiltshire/.local/lib/python3.9/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
[2024-01-10 12:06:06] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 77a5ecab54a8f319116fdfd457a3b315.
